//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _IPC2_IGameOthello.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleJuego
    {
        public int id_detalleJuego { get; set; }
        public Nullable<int> Id_juego { get; set; }
        public int jugador1 { get; set; }
        public int jugador2 { get; set; }
        public Nullable<int> perdedor { get; set; }
        public Nullable<byte> punteo_jugador1 { get; set; }
        public Nullable<byte> punteo_jugador2 { get; set; }
        public Nullable<byte> movs_jugador1 { get; set; }
        public Nullable<byte> movs_jugador2 { get; set; }
    
        public virtual Juego Juego { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
    }
}
