//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _IPC2_IGameOthello.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleTorneo
    {
        public int id_detalleTorneo { get; set; }
        public Nullable<byte> ronda_torneo { get; set; }
        public Nullable<int> id_juego { get; set; }
        public Nullable<int> id_torneo { get; set; }
    
        public virtual Juego Juego { get; set; }
        public virtual Torneo Torneo { get; set; }
    }
}
